// Build-time data access. Everything the site shows comes from src/data/tidy.json, which is
// generated by the Python pipeline (`npm run data`). Never hard-code a statistic in a component.
import rows from '../data/tidy.json';
import meta from '../data/meta.json';

export interface Row {
  year: number;
  period_start: string;
  period_end: string;
  geo_level: 'country' | 'state' | 'district' | 'city' | 'aggregate';
  geo_code: string;
  geo_name: string;
  dataset: string;
  metric: string;
  dimension: string;
  dimension_value: string;
  value: number;
  unit: string;
  source_org: string;
  tier: 1 | 2 | 3;
  as_of_date: string;
  retrieved_on: string;
  source_table: string;
  source_edition: string;
  source_url: string;
  notes: string;
}

export const ALL: Row[] = rows as Row[];
export const META = meta as {
  generated_on: string;
  row_count: number;
  parsed_ncrb_rows: number;
  outstanding_tables: string[];
  warnings: string[];
  known_discrepancies: string[];
  datasets: string[];
  checks_passed: number;
};

export interface Q {
  dataset: string;
  metric?: string;
  geo?: string;
  year?: number;
  dim?: string;
  org?: string;
  maxTier?: 1 | 2 | 3;
}

export function where(q: Q): Row[] {
  return ALL.filter(
    (r) =>
      r.dataset === q.dataset &&
      (q.metric === undefined || r.metric === q.metric) &&
      (q.geo === undefined || r.geo_code === q.geo) &&
      (q.year === undefined || r.year === q.year) &&
      (q.dim === undefined || r.dimension_value === q.dim) &&
      (q.org === undefined || r.source_org === q.org) &&
      (q.maxTier === undefined || r.tier <= q.maxTier),
  );
}

/** Exactly one row, or throw at build time — a missing number must break the build, not render blank. */
export function one(q: Q): Row {
  const r = where(q);
  if (r.length !== 1) throw new Error(`data: expected 1 row for ${JSON.stringify(q)}, got ${r.length}`);
  return r[0];
}

export function maybe(q: Q): Row | undefined {
  const r = where(q);
  return r.length === 1 ? r[0] : undefined;
}

export function years(dataset: string, geo?: string): number[] {
  return [...new Set(where({ dataset, geo }).map((r) => r.year))].sort((a, b) => a - b);
}

export function latestYear(dataset: string, geo?: string): number | undefined {
  const y = years(dataset, geo);
  return y.length ? y[y.length - 1] : undefined;
}

/** Geo codes (state level) that have data for a dataset/year. */
export function geosWith(dataset: string, year: number, level: Row['geo_level'] = 'state'): string[] {
  return [...new Set(where({ dataset, year }).filter((r) => r.geo_level === level).map((r) => r.geo_code))];
}

// ── formatting ──────────────────────────────────────────────────────────────
const inFmt = new Intl.NumberFormat('en-IN');
export const fmt = (n: number, digits = 0) =>
  new Intl.NumberFormat('en-IN', { maximumFractionDigits: digits, minimumFractionDigits: digits }).format(n);
export const fmtInt = (n: number) => inFmt.format(Math.round(n));
export const pct = (part: number, whole: number, digits = 1) => fmt((part / whole) * 100, digits);

/** "19.3 lakh" style for large counts (used sparingly, always with the exact figure nearby). */
export function lakh(n: number, digits = 1) {
  if (n >= 1e7) return `${fmt(n / 1e7, digits)} crore`;
  if (n >= 1e5) return `${fmt(n / 1e5, digits)} lakh`;
  return fmtInt(n);
}

export function daysInYear(y: number) {
  return (y % 4 === 0 && y % 100 !== 0) || y % 400 === 0 ? 366 : 365;
}

const MONTHS_EN = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
const MONTHS_TA = ['ஜன', 'பிப்', 'மார்', 'ஏப்', 'மே', 'ஜூன்', 'ஜூலை', 'ஆக', 'செப்', 'அக்', 'நவ', 'டிச'];
export function fmtDate(iso: string, lang: 'en' | 'ta' = 'en', withDay = true) {
  const [y, m, d] = iso.split('-').map(Number);
  const mon = (lang === 'ta' ? MONTHS_TA : MONTHS_EN)[m - 1];
  return withDay ? `${d} ${mon} ${y}` : `${mon} ${y}`;
}

/** A row's time period in words: "2024", "Jan–Jul 2026", "as on 30 Jul 2026". */
export function periodLabel(r: Row, lang: 'en' | 'ta' = 'en') {
  const M = lang === 'ta' ? MONTHS_TA : MONTHS_EN;
  if (r.period_start === r.period_end) return (lang === 'ta' ? '' : 'as on ') + fmtDate(r.period_end, lang) + (lang === 'ta' ? ' நிலவரப்படி' : '');
  const [ys, ms, ds] = r.period_start.split('-').map(Number);
  const [ye, me, de] = r.period_end.split('-').map(Number);
  if (ms === 1 && ds === 1 && me === 12 && de === 31) return ys === ye ? `${ys}` : `${ys}–${ye}`;
  if (ys === ye) return `${M[ms - 1]}–${M[me - 1]} ${ye}`;
  return `${M[ms - 1]} ${ys} – ${M[me - 1]} ${ye}`;
}

export const ORG_LABEL: Record<string, string> = {
  NCRB: 'NCRB',
  TN_SCRB: 'TN State Crime Records Bureau',
  TN_POLICY_NOTE: 'TN Police Policy Note',
  TN_POLICE: 'Tamil Nadu Police',
  MoLJ: 'Ministry of Law & Justice',
  MADRAS_HC: 'Madras High Court',
  NJDG: 'National Judicial Data Grid',
  NCMEC: 'NCMEC CyberTipline',
  KERALA_POLICE: 'Kerala Police',
  PRESS: 'Press report',
  VIDHI: 'Vidhi Centre for Legal Policy',
};
